PERCISION = 32

FULL_RANGE = 1 << PERCISION
HALF_RANGE = FULL_RANGE >> 1
QUARTER_RANGE = HALF_RANGE >> 1
THREE_QUARTER_RANGE = HALF_RANGE + QUARTER_RANGE

FULL_RANGE_BITMASK = FULL_RANGE - 1
EOF_MARKER = "𒐫"
