PRECISION = 32

FULL_RANGE = 1 << PRECISION
HALF_RANGE = FULL_RANGE >> 1
QUARTER_RANGE = HALF_RANGE >> 1
THREE_QUARTER_RANGE = HALF_RANGE + QUARTER_RANGE

FULL_RANGE_BITMASK = FULL_RANGE - 1


SYMBOL_BIT_COUNT = 8
SYMBOL_FREQUENCY_BITLENGTH_BIT_COUNT = 4
