ENDIAN: "big"

SOF_MARKER: "\x0f"
EOF_MARKER: "\x0f"

SYMBOL_BITSIZE: 8

CTYPE_INT_DTYPE_BITSIZE: {
    # --- char ---#
    b: 8,
    B: 8,
    # --- short ---#
    h: 16,
    H: 16,
    # --- integer ---#
    i: 32,
    I: 32,
    # --- long ---#
    l: 32,
    L: 32,
    # --- long ---#
    q: 64,
    Q: 64,
}

HuffmanCoding:
  NUM_CODELENGTH: 16
  CODELENGTH_BITSIZE: 8

ArithmeticCoding:
  PRECISION: 32